### ISSUE TITLE
import  errors?  

### ISSUE THREAD

**Issue by tiandamiao** [aimagelab/novelty-detection#3]
from torch.utils.data.dataloader import _use_shared_memory
from torch.utils.data.dataloader import int_classes
from torch.utils.data.dataloader import numpy_type_map
from torch.utils.data.dataloader import string_classes

**Comment by LBAMAD** [comment]
> from torch.utils.data.dataloader import _use_shared_memory from torch.utils.data.dataloader import int_classes from torch.utils.data.dataloader import numpy_type_map from torch.utils.data.dataloader import string_classes

I have encountered the same problem. Can you tell me how did you solve it.Thank you！
