### ISSUE TITLE
Train own dataset

### ISSUE THREAD

**Issue by lte91** [aimagelab/novelty-detection#8]
Hey, 

thanks for this great work and the release of the code.
I would like to train on my own data, but I can't find a train.py file. So I would like to ask, how can I train on my own data?

**Comment by DavideA** [comment]
Hi,

for a minimal example of training code, please refer to [this issue](https://github.com/aimagelab/novelty-detection/issues/1#issuecomment-476117497).

Best,
D

**Comment by lte91** [comment]
Hey, 

thank you for your quick reply. I will take a look there. 

best regards,
lte91
